### ISSUE TITLE
Getting error "java.lang.RuntimeException: error loading the erlyberly module" while connecting to target node 

### ISSUE THREAD

**Issue by GeitRavi** [andytill/erlyberly#174]
we are trying to connect the target node machine just passing two variable target node & cookie in UI.
But we getting error  
$ java -jar erlyberly-0.7.1-SNAPSHOT-runnable.jar
Failed to start epmd: java.io.IOException: Cannot run program "epmd": CreateProcess error=2, The system cannot find the file specified
Exception in thread "Erlyberly Connector Thread" java.lang.RuntimeException: error loading the erlyberly module, result was error
        at erlyberly.node.NodeAPI.loadErlyberlyError(NodeAPI.java:461)
        at erlyberly.node.NodeAPI.compileAndLoadRemoteErlyberly(NodeAPI.java:450)
        at erlyberly.node.NodeAPI.loadRemoteErlyberly(NodeAPI.java:431)
        at erlyberly.node.NodeAPI.connect(NodeAPI.java:228)
        at erlyberly.node.NodeAPI.manualConnect(NodeAPI.java:203)
        at erlyberly.ConnectionView$ConnectorThead.run(ConnectionView.java:335)

Software version:
Java 8
erlyberly-0.7.1-SNAPSHOT-runnable.jar
OTP version: 20 
Window machine.

Can anyone please help me out on this issue.

**Comment by aboroska** [comment]
On Windows epmd has to be started manually if I remember correctly. Try starting an Erlang shell which should normally start epmd for you. If it doesn't start it then find epmd.exe and run it. Hope that helps.

**Comment by GeitRavi** [comment]
Thanks for your response.

Sorry I missed to mentioned that epmd.exe process running in the background, still getting the same error.

Is any specific OTP Erlang version is required to support erlyberly-0.7.1-SNAPSHOT-runnable.jar file?

**Comment by GeitRavi** [comment]
Can you please add or provide the correct erlyberly-0.7.1-SNAPSHOT-runnable.jar file to GitHub repo, so that we can use that file directly but not sure that is possible or not?

**Comment by andytill** [comment]
Is `epmd` on the PATH?

**Comment by andytill** [comment]
Is it possible that erlyberly was built with a different version of OTP than what you're running it on?

**Comment by GeitRavi** [comment]
We are using the same OTP version(OTP 22) for erlybery code compilation and starting erlyberly runnable jar file.

If we want to connect a remote node machine (node erlang machine) what all setting we have to do?

Can you please share the example of how to connect the remote machine. e.g (how we can pass the remote login details - machine username & machine password)

**Comment by andytill** [comment]
If you run erlyberly on OTP 22 and the application using OTP 20 (as in the issue description) there might be a problem.

When erlyberly connects, it sends a beam file which is loaded into the remote VM, erlyberly.erl. This is compiled with erlyberly, not the remote nodes OTP version.

An older OTP will not read a newer OTP as a rule.

To get this error, erlyberly must have connected in successfully using erlang distribution.
