### ISSUE TITLE
Crashes on start up on Rasberry Pi [Loading Modules on startup]

### ISSUE THREAD

**Issue by ruanpienaar** [andytill/erlyberly#31]
My Raspberry pi is 1) slow and 2) a bit Busy, so i'd expect side effects. 
( Even OTP's observer is acts a bit weird, with crashes from time to time ).

Modified the requestFunctions function a little to be more verbose:

``` Java
    public synchronized OtpErlangList requestFunctions() throws Exception {
        assert !Platform.isFxApplicationThread() : "cannot run this method from the FX thread";

        sendRPC("erlyberly", "module_functions", new OtpErlangList());

        OtpErlangObject result = receiveRPC();
        System.out.println(result);
        OtpErlangList l = (OtpErlangList) result;
        return l;

        //return (OtpErlangList) receiveRPC();
    }
```

This happens, when Erlyberly is started: 

```
------------------------------------------------------------------------
Building erlyberly 0.6.1
------------------------------------------------------------------------

--- exec-maven-plugin:1.2.1:exec (default-cli) @ erlyberly ---
May 28, 2015 10:18:30 PM com.sun.javafx.css.parser.CSSParser declaration
WARNING: CSS Error parsing '*{-fx-font-family: FontAwesome; -fx-font-size: 2em;null}: Expected COLON at [1,55]
null
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
    at erlyberly.DbgView.buildObjectTreeRoot(DbgView.java:481)
    at erlyberly.DbgView$$Lambda$406/1384178901.callback(Unknown Source)
    at erlyberly.DbgController$GetModulesThread.lambda$run$3(DbgController.java:194)
    at erlyberly.DbgController$GetModulesThread$$Lambda$411/1277535706.run(Unknown Source)
    at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
    at com.sun.javafx.application.PlatformImpl$$Lambda$49/324427784.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
    at com.sun.javafx.application.PlatformImpl$$Lambda$48/237061348.run(Unknown Source)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

```

Module functions load fine, after i click on refresh modules.

**Comment by ruanpienaar** [comment]
What's interesting is, the erlyberly startup ( i'd consider to be lightweight ) actually flatlines the raspberry pi's CPU to 100+%

( Maybe that causes some unknow dealt with waiting ... )
( i can imagine this might happen on system's under heavy load )

![screen shot 2015-05-28 at 23 09 19](https://cloud.githubusercontent.com/assets/584394/7872312/f2b1a84c-058e-11e5-8f7d-ddeb8467d22c.png)

**Comment by andytill** [comment]
Interesting, do you know roughly how many modules were loaded at the time?

Also, is it reproducible if you load the erlyberly module without erlyberly and call `erlyberly:module_functions()`?

**Comment by ruanpienaar** [comment]
I'll have to re-test

**Comment by andytill** [comment]
Closing. I am surprised and delighted that erlyberly runs on Rasberry Pi at all, but if this is a load issue it is not easily fixed without cutting features.

**Comment by ruanpienaar** [comment]
EB was running on my macbook pro.
Then connecting to a erlang node running on a Raspberry pi.
The delay seems to come from calling code:all_loaded(), which seems to take forever
( longer than EB allows to wait )
