### ISSUE TITLE
Exceptions thrown when sorting traces by column

### ISSUE THREAD

**Issue by andytill** [andytill/erlyberly#47]
Exceptions thrown when sorting traces by column.

	Exception in thread "JavaFX Application Thread" java.lang.UnsupportedOperationException
		at java.util.AbstractList.remove(AbstractList.java:161)
		at java.util.AbstractList$Itr.remove(AbstractList.java:374)
		at java.util.AbstractList.removeRange(AbstractList.java:571)
		at javafx.collections.ObservableListBase.remove(ObservableListBase.java:270)
		at com.sun.javafx.binding.BidirectionalContentBinding$ListContentBinding.onChanged(BidirectionalContentBinding.java:131)
		at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
		at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
		at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
		at com.sun.javafx.collections.ObservableListWrapper.sort(ObservableListWrapper.java:226)
		at javafx.collections.FXCollections.sort(FXCollections.java:671)
		at javafx.scene.control.TableView$3.call(TableView.java:467)
		at javafx.scene.control.TableView$3.call(TableView.java:431)
		at javafx.scene.control.TableView.sort(TableView.java:1519)
		at javafx.scene.control.TableView.doSort(TableView.java:1578)
		at javafx.scene.control.TableView.lambda$new$40(TableView.java:734)
		at javafx.scene.control.TableView$$Lambda$136/2129761332.invalidated(Unknown Source)
		at javafx.beans.WeakInvalidationListener.invalidated(WeakInvalidationListener.java:83)
		at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:349)
		at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
		at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105)
		at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
		at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
		at javafx.scene.control.TableColumn.setSortType(TableColumn.java:459)
		at com.sun.javafx.scene.control.TableColumnSortTypeWrapper.setSortType(TableColumnSortTypeWrapper.java:54)
		at com.sun.javafx.scene.control.skin.TableColumnHeader.sortColumn(TableColumnHeader.java:770)
		at com.sun.javafx.scene.control.skin.TableColumnHeader.lambda$static$55(TableColumnHeader.java:243)
		at com.sun.javafx.scene.control.skin.TableColumnHeader$$Lambda$304/113933935.handle(Unknown Source)
		at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
		at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
		at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
		at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
		at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
		at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
		at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
		at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
		at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
		at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
		at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
		at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
		at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
		at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
		at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
		at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
		at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
		at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
		at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
		at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
		at javafx.event.Event.fireEvent(Event.java:198)
		at javafx.scene.Scene$MouseHandler.process(Scene.java:3758)
		at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3486)
		at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
		at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2495)
		at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:350)
		at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:275)
		at java.security.AccessController.doPrivileged(Native Method)
		at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$350(GlassViewEventHandler.java:385)
		at com.sun.javafx.tk.quantum.GlassViewEventHandler$$Lambda$444/1972213213.get(Unknown Source)
		at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:404)
		at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:384)
		at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
		at com.sun.glass.ui.View.notifyMouse(View.java:927)

If the filteredTraces field in DbgTraceView is set instead of bound:

    tracesBox.setItems(filteredTraces);

Then the traces cannot be filtered by column at all.

**Comment by andytill** [comment]
Fix in commit 7fbee76d27e1c36645cc92c6c8a7e7a84337c983
