### ISSUE TITLE
Is OpenJDK supported for running the released JAR?

### ISSUE THREAD

**Issue by lucafavatella** [andytill/erlyberly#51]
The JAR looks working with Oracle JDK but not with OpenJDK. Is this expected?

In the readme I read `You will need Java 8u20 or higher to run erlyberly [...]` - it is not clear to me whether this excludes any other JDK different from the Oracle's one.

Is this a bug in OpenJDK? Or a bug in Oracle JDK? Or is the JAR malformed (e.g. classpath not set in manifest) in a way that triggers JDK implementation-dependent behaviour?

Details below.

I fetched the package:
```
$ curl -LO https://github.com/andytill/erlyberly/releases/download/0.6.7/erlyberly-0.6.7-runnable.jar
...
MD5 (erlyberly-0.6.7-runnable.jar) = d2c424439bca6ca7ba4dba6ea4e607d4
```

OpenJDK cannot find the entry point:
```
$ java -version
openjdk version "1.8.0_66-internal"
OpenJDK Runtime Environment (build 1.8.0_66-internal-b17)
OpenJDK 64-Bit Server VM (build 25.66-b17, mixed mode)

$ java -jar erlyberly-0.6.7-runnable.jar
Error: Could not find or load main class erlyberly.ErlyBerly
```

Oracle JDK manages to find the entry point in the JAR (it fails as I have no display but that is out of scope):
```
$ java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

$ java -jar erlyberly-0.6.7-runnable.jar
Exception in thread "main" java.lang.reflect.InvocationTargetException
...
Caused by: java.lang.UnsupportedOperationException: Unable to open DISPLAY
...
```

I checked that variables `CLASSPATH` and `JAVA_HOME` are unset (not empty string - really unset) for both examples above.

**Comment by andytill** [comment]
Interesting that you mentioned the manifest does not have the `Class-Path` attribute, does it work on OpenJDK if you set it to the jar name in the `META-INF/MANIFEST.MF` manually?

I am only testing using the Oracle JDK and don't want to test on multiple JDKs for every change. I'd be more than happy to have OpenJDK support via contributions though.

**Comment by lucafavatella** [comment]
> Interesting that you mentioned the manifest does not have the Class-Path attribute, does it work on OpenJDK if you set it to the jar name in the META-INF/MANIFEST.MF manually?

I tried to set it to the jar name `Class-Path: erlyberly-0.6.7-runnable.jar` - same result. I tried to set it to `.` - same result. I tried to set it to `erlyberly` - same result.

(Main commands I used:
* `jar -xf erlyberly-0.6.7-runnable.jar META-INF/MANIFEST.MF`
* `jar ufm erlyberly-0.6.7-runnable.jar META-INF/MANIFEST.MF`
)

**Comment by lucafavatella** [comment]
Maybe OpenJDK does not support javafx package? Or maybe my OpenJDK installation is broken.

```
$ java -verbose -Xdiag -jar erlyberly-0.6.7-runnable.jar
...
Error: Could not find or load main class erlyberly.ErlyBerly
...
java.lang.NoClassDefFoundError: javafx/application/Application
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 13 more
...
```

**Comment by lucafavatella** [comment]
It looks like I have a version of OpenJDK without JavaFX - so my bad. Apologies for the noise.

Ref https://stackoverflow.com/questions/18547362/javafx-and-openjdk
