### ISSUE TITLE
Large Crash Reports

### ISSUE THREAD

**Issue by ruanpienaar** [andytill/erlyberly#75]
Can we limit the text in the Crash report dropdown. ( say 200 characters, and then append ... )
CrashReport bla bla bla bla bla bla bla bla bla ....
CrashReport bla bla bla bla bla bla bla bla bla ....

Currently when large crash reports are shown on the UI, then it overlaps
way past the boundaries of the monitor, which is unreadable.

**Comment by andytill** [comment]
This throws an exception, on Mac OS at least, might be related to #92 

```
2016-09-25 13:07:26.526 java[939:5697475] GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_EXT
java.lang.RuntimeException: Requested texture dimensions (26658x182) require dimensions (0x182) that exceed maximum texture size (16384)
        at com.sun.prism.es2.ES2RTTexture.create(ES2RTTexture.java:220)
        at com.sun.prism.es2.ES2ResourceFactory.createRTTexture(ES2ResourceFactory.java:152)
        at com.sun.prism.es2.ES2SwapChain.createGraphics(ES2SwapChain.java:217)
        at com.sun.prism.es2.ES2SwapChain.createGraphics(ES2SwapChain.java:40)
        at com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:87)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        at java.lang.Thread.run(Thread.java:745)
```
